### ISSUE TITLE
Add formula for kplex

### ISSUE THREAD

**Issue by caesar** [nohal/homebrew-navutils#1]
Hey Pavel, would you accept a PR to add a formula for [kplex](https://github.com/stripydog/kplex)?

I have a formula I use locally, with a launchd plist and everything, I'd be happy to send a PR (and also to keep it up to date in the future with new kplex releases).

Of course I could maintain it elsewhere but since you have a useful tap for nav utilities, it seems like a good place for it! What do you think?

**Comment by nohal** [comment]
Hi Caesar...

Yep, sure, no need for even more granularity...
