### ISSUE TITLE
RTL_AIS

### ISSUE THREAD

**Issue by VincentWerbrouck** [nohal/homebrew-navutils#3]
I have had a problem to install RTL_AIS on my macbook pro M1, OS Sonoma 14.2.1; here is the message I have received. Thus unable to decode AIS from my RTL-DSR

Last 15 lines from /Users/vincentwerbrouck/Library/Logs/Homebrew/rtl-ais/01.make:
clang -c aisdecoder/lib/hmalloc.c -o aisdecoder/lib/hmalloc.o -O2 -g -Wall -W  -I./aisdecoder -I ./aisdecoder/lib -I./tcp_listener -I/usr/local/include/ -I/tmp/libusb/include/libusb-1.0 -I/tmp/rtl-sdr/include
clang -c aisdecoder/lib/filter.c -o aisdecoder/lib/filter.o -O2 -g -Wall -W  -I./aisdecoder -I ./aisdecoder/lib -I./tcp_listener -I/usr/local/include/ -I/tmp/libusb/include/libusb-1.0 -I/tmp/rtl-sdr/include
clang -c tcp_listener/tcp_listener.c -o tcp_listener/tcp_listener.o -O2 -g -Wall -W  -I./aisdecoder -I ./aisdecoder/lib -I./tcp_listener -I/usr/local/include/ -I/tmp/libusb/include/libusb-1.0 -I/tmp/rtl-sdr/include
tcp_listener/tcp_listener.c:242:43: error: call to undeclared function 'inet_ntoa'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        sprintf(p_tcp_sock->from_ip, "%.*s", 19, inet_ntoa(p_tcp_sock->cli_addr.sin_addr));
                                                 ^
tcp_listener/tcp_listener.c:259:2: error: call to undeclared function 'gettimeofday'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        gettimeofday(&now, NULL);
        ^
tcp_listener/tcp_listener.c:294:2: error: call to undeclared function 'gettimeofday'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        gettimeofday(&new_node->timestamp, NULL);
        ^
3 errors generated.
make: *** [tcp_listener/tcp_listener.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by nohal** [comment]
I have updated the `rtl-ais` formula to the current upstream patched to actually build on Apple Silicon (just added paths to handle Homebrew being under `/opt/homebrew` and not `/usr/local` in the `Makefile`)

I have no means to test it with actual hardware, so all I can say is it builds and starts.

Just do `brew update ; brew install nohal/navutils/rtl-ais` and you should be good to go.

**Comment by VincentWerbrouck** [comment]
Great thank you, it works


Vincent Werbrouck

10 Le Weya
1457 Nil-Saint-Vincent
Belgique
+32 475 85 37 78




Le 12 janv. 2024 à 17:05, Pavel Kalian ***@***.***> a écrit :



I have updated the rtl-ais formula to the current upstream patched to actually build on Apple Silicon (just added paths to handle Homebrew being under /opt/homebrew and not /usr/local in the Makefile)

I have no means to test it with actual hardware, so all I can say is it builds and starts.

Just do brew update ; brew install nohal/navutils/rtl-ais and you should be good to go.
